### ISSUE TITLE
Backport Request: aws-sdk-cpp update for scarthgap

### ISSUE THREAD

**Issue by kledom** [aws4embeddedlinux/meta-aws#10437]
Hello,
I’m encountering an issue with meta-aws for Yocto 5.0 (Scarthgap) that has already been resolved in `aws-sdk-cpp` version 1.11.443 via [commit 54ff0aae53](https://github.com/aws/aws-sdk-cpp/commit/54ff0aae53dd889b200c800b5dcc09602a6b690b).

However, while updates for dependencies like `aws-crt-cpp` are consistently backported to Scarthgap, this does not appear to be the case for `aws-sdk-cpp`.

Could you clarify the rationale behind this discrepancy? Additionally, is there a timeline or plan for updating `aws-sdk-cpp` on Scarthgap?

Thank you for your assistance!

**Comment by thomas-roos** [comment]
Hi, thanks for asking. Usually everything that can be backported, will be backported to active releases. -next branches are fast forwarded merged to release branches usually Mondays.
The automatic backport for this seems to be broken since two weeks.
It is already on my list for Monday, but feel free to submit a pr for the upgrade to scarthgap next branch. Then it is for sure on the scarthgap release on Monday.
Hope that helps.
Cheers, Thomas
